version: '2'
services:
  zigbee2moremqtt:
    container_name: zigbee2moremqtt
    image: thetonyfav/zigbee2moremqtt:latest
    environment:
    - "MQTT_HOST=10.0.0.255"
    - "MQTT_PORT=1883"
    - "MQTT_USER=user"
    - "MQTT_PASSWORD=pass"
    - "MQTT_CLIENT=zigbee2moremqtt"
    - "MQTT_QOS=1"
    restart: unless-stopped