version: '2'
services:
  zigbee2moremqtt:
    container_name: zigbee2moremqtt
    image: thetonyfav/zigbee2moremqtt:latest
    environment:
    - "MQTT_HOST=10.0.0.255"
    - "MQTT_PORT=1883"
    - "MQTT_USER=user"
    - "MQTT_PASSWORD=pass"
    - "MQTT_CLIENT=zigbee2moremqtt"
    - "MQTT_QOS=1"
    - "SAGE_SWITCH_TOPIC=zigbee2mqtt/Sage_Switch/"
    - "ON_1_PRESS_TOPIC=cmnd/tasmota_AAAAAA/Power2"
    - "ON_2_PRESS_TOPIC=cmnd/tasmota_BBBBBB/Power1"
    - "ON_3_PRESS_TOPIC=cmnd/tasmota_CCCCCC/Power1"
    - "OFF_1_PRESS_TOPIC=cmnd/tasmota_AAAAAA/Power1"
    - "OFF_2_PRESS_TOPIC=cmnd/tasmota_DDDDDD/Power1"
    - "OFF_3_PRESS_TOPIC=cmnd/tasmota_CCCCCC/Power1"
    - "ON_1_PRESS_PAYLOAD=TOGGLE"
    - "ON_2_PRESS_PAYLOAD=TOGGLE"
    - "ON_3_PRESS_PAYLOAD=ON"
    - "OFF_1_PRESS_PAYLOAD=TOGGLE"
    - "OFF_2_PRESS_PAYLOAD=TOGGLE"
    - "OFF_3_PRESS_PAYLOAD=OFF"
    restart: unless-stopped